version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - .env
    environment:
      INNGEST_REGISTER_URL: http://host.docker.internal:8288/fn/register
    volumes:
      - .:/app
    ports:
      - 3000:3000
